name: Build source

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            build-command: 'npm run build:mac'
            asset-path: 'build/*.dmg'
          - os: windows-latest
            build-command: 'npm run build:windows'
            asset-path: 'build/*.exe'
          - os: ubuntu-latest
            build-command: 'npm run build:linux'
            asset-path: 'build/*.AppImage'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: ${{ matrix.build-command }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN  }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
