name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run build:windows
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN  }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Linux
        run: npm run build:linux
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN  }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

  build-mac:
    runs-on: macOS-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for macOS
        run: npm run build:mac -- --publish=never
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN  }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

  release:
    needs: [build-windows, build-linux, build-mac]
    runs-on: ubuntu-latest

    steps:
      # Create the GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # Upload the assets
      - name: Upload Release Assets
        run: |
          for file in build/*; do
            if [ -f "$file" ]; then
              echo "Uploading $file ..."
              gh release upload ${{ github.ref_name }} $file
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
