name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            build-command: 'npm run build:mac'
            asset-path: 'build/*.dmg'
          - os: windows-latest
            build-command: 'npm run build:windows'
            asset-path: 'build/*.exe'
          - os: ubuntu-latest
            build-command: 'npm run build:linux'
            asset-path: 'build/*.AppImage'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: ${{ matrix.build-command }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN  }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.asset-path }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          path: build-assets

      - name: Upload Release Assets
        run: |
          for file in build-assets/*; do
            asset_name=$(basename $file)
            content_type=$(file --mime-type -b $file)
            echo "Uploading $file ($content_type)..."
            gh release upload ${{ steps.create_release.outputs.tag_name }} $file --name "$asset_name" --type "$content_type"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
